apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-operator
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
      app.kubernetes.io/component: operator
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - keycloak-system
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-operator-metrics
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: operator