name: 'Unit Tests & Coverage'
description: 'Run unit tests with coverage reporting'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  codecov-token:
    description: 'Codecov token for uploads'
    required: true
  github-actor:
    description: 'GitHub actor name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: ./.github/actions/setup-tools

    - name: Run unit tests
      shell: bash
      run: task test:unit

    - name: Upload unit coverage artifact for combining
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: unit-coverage
        path: |
          .coverage
          coverage.xml
        retention-days: 1
