name: 'Code Quality'
description: 'Run code quality checks and validate decision records'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  yq-version:
    description: 'yq version to use'
    required: false
    default: 'v4.44.3'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: ./.github/actions/setup-tools
      with:
        yq-version: ${{ inputs.yq-version }}

    - name: Run quality checks
      shell: bash
      run: task quality:check

    - name: Validate Decision Records
      shell: bash
      run: task quality:validate-decisions
      if: hashFiles('docs/decisions/*.yaml') != ''
