# Docker Compose for local development and testing
# Usage: docker-compose up -d

services:
  # PostgreSQL database for Keycloak
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Keycloak instance for testing
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Keycloak Operator (for development)
  keycloak-operator:
    build: .
    environment:
      # Kopf configuration
      KOPF_LOG_LEVEL: DEBUG
      KOPF_VERBOSE: "true"

      # Operator configuration
      KEYCLOAK_OPERATOR_LOG_LEVEL: DEBUG
      KEYCLOAK_OPERATOR_NAMESPACE: default
      KEYCLOAK_OPERATOR_WATCH_NAMESPACE: ""  # Watch all namespaces

      # Development settings
      KEYCLOAK_OPERATOR_DEV_MODE: "true"
      KEYCLOAK_OPERATOR_DRY_RUN: "false"

      # Metrics and monitoring
      KEYCLOAK_OPERATOR_METRICS_PORT: 8080
      KEYCLOAK_OPERATOR_HEALTH_PORT: 8081
    ports:
      - "8090:8080"  # Metrics
      - "8091:8081"  # Health
    volumes:
      # Mount kubeconfig for local development
      - ~/.kube:/home/keycloak/.kube:ro
      # Mount source code for development (optional)
      - ./src:/app/src:ro
    depends_on:
      keycloak:
        condition: service_healthy
    profiles:
      - dev  # Only start with --profile dev

volumes:
  postgres_data: