name: 'Publish Release Documentation'
description: 'Build and publish versioned release documentation to GitHub Pages'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  chart-path:
    description: 'Path to the operator chart'
    required: false
    default: 'charts/keycloak-operator'
  yq-version:
    description: 'yq version to use'
    required: false
    default: 'v4.44.3'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - uses: ./.github/actions/setup-tools

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy versioned docs with mike
      shell: bash
      run: task docs:publish-release
