name: 'Build Operator Image'
description: 'Build the operator Docker image (test target with coverage support)'

inputs:
  cache-key-prefix:
    description: 'Prefix for cache key'
    required: false
    default: 'buildx'

outputs:
  image-artifact:
    description: 'Name of the uploaded image artifact'
    value: 'operator-image'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get build args
      id: meta
      shell: bash
      run: |
        VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
        REVISION=${{ github.sha }}
        CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "revision=${REVISION}" >> $GITHUB_OUTPUT
        echo "created=${CREATED}" >> $GITHUB_OUTPUT

    - name: Build operator image (test target with coverage)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: images/operator/Dockerfile
        target: test
        platforms: linux/amd64
        tags: keycloak-operator:test
        build-args: |
          VERSION=${{ steps.meta.outputs.version }}
          REVISION=${{ steps.meta.outputs.revision }}
          CREATED=${{ steps.meta.outputs.created }}
        outputs: type=docker,dest=/tmp/operator-test.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Upload image artifact
      uses: actions/upload-artifact@v5
      with:
        name: operator-image
        path: /tmp/operator-test.tar
        retention-days: 1
