name: 'Update Dev Documentation'
description: 'Build and publish development documentation to GitHub Pages'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - uses: ./.github/actions/setup-task

    - name: Deploy dev docs with mike
      shell: bash
      run: task docs:publish-dev
