name: Feature request
description: Propose a new capability or enhancement
title: "[feature]: <short summary>"
labels:
  - enhancement
  - needs-triage
body:
  - type: textarea
    id: summary
    attributes:
      label: summary
      description: One sentence describing the desired capability.
      placeholder: Support automatic rotation of Keycloak admin credentials
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: problem-or-opportunity
      description: What real workflow gap or risk does this solve? Avoid solutions here.
      placeholder: Manual admin credential rotation causes drift and breaks downstream automation.
    validations:
      required: true
  - type: textarea
    id: proposed
    attributes:
      label: proposed-solution
      description: Describe intended behavior. Use structured sections. Include CRD changes if any.
      placeholder: |
        user-story:
          As a cluster operator I want admin credentials rotated automatically
          so that long-lived static secrets are eliminated.

        api-changes:
          Keycloak (CRD) spec additions:
            spec:
              adminCredentialRotation:
                enabled: true
                schedule: "0 */6 * * *"
                gracePeriod: 10m
          No breaking removals.

        controller-behavior:
          - On schedule tick, generate new credential via Keycloak admin API
          - Update Kubernetes Secret <name>-admin
          - Invalidate old credential after gracePeriod
          - Emit Event: Type=Normal Reason=AdminCredentialsRotated

        observability:
          metrics:
            - keycloak_operator_admin_secret_rotations_total (counter)
            - keycloak_operator_admin_secret_rotation_failures_total (counter)
          log-context:
            component=admin-rotation client=<id>

        failure-modes:
          - Keycloak unreachable → retry with exponential backoff
          - Secret update conflict → patch retry

        security:
          - Zero plaintext logging
          - Secret recreated with 'immutable' false to allow patch

        out-of-scope:
          - Custom rotation webhooks
    validations:
      required: true
  