apiVersion: keycloak.mdvr.nl/v1
kind: KeycloakClient
metadata:
  name: service-account-client
  namespace: default
spec:
  realm_ref:
    name: service-account-realm
    namespace: default

  client_id: service-account-app
  secret:
    name: service-account-client-secret
    namespace: default
  service_account_enabled: true

  redirect_uris:
    - "http://localhost:3000/*"

  web_origins:
    - "http://localhost:3000"

  realm_roles:
    - api-user

  service_account_roles:
    realm:
      realm_roles:
        - api-user

  protocol_mappers:
    - name: service-account-username
      protocol: openid-connect
      protocolMapper: oidc-usermodel-attribute-mapper
      config:
        access.token.claim: "true"
        claim.name: preferred_username
        jsonType.label: String
        user.attribute: serviceAccountClientId
