name: 'Publish Operator Image'
description: 'Build and publish the operator image to GHCR with attestations'

inputs:
  registry:
    description: 'Container registry'
    required: true
  image-name:
    description: 'Image name (repository)'
    required: true
  operator-version:
    description: 'Operator version to publish'
    required: true
  github-token:
    description: 'GitHub token for registry access'
    required: true
  github-actor:
    description: 'GitHub actor name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Extract version
      id: version
      shell: bash
      run: |
        VERSION="${{ inputs.operator-version }}"
        REVISION=${{ github.sha }}
        CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "revision=${REVISION}" >> $GITHUB_OUTPUT
        echo "created=${CREATED}" >> $GITHUB_OUTPUT
        echo "Publishing operator version: ${VERSION}"

    - name: Generate tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=latest
          type=raw,value=v${{ steps.version.outputs.version }}
          type=raw,value=${{ steps.version.outputs.version }}
        labels: |
          org.opencontainers.image.title=Keycloak Operator
          org.opencontainers.image.description=GitOps-compatible Kubernetes operator for Keycloak
          org.opencontainers.image.vendor=Michaël de Vries
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.version=v${{ steps.version.outputs.version }}
          org.opencontainers.image.source=https://github.com/vriesdemichael/keycloak-operator
          org.opencontainers.image.url=https://github.com/vriesdemichael/keycloak-operator

    - uses: ./.github/actions/setup-tools

    - name: Build and push
      id: build
      shell: bash
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        LABELS: ${{ steps.meta.outputs.labels }}
      run: |
        task image:publish \
          VERSION="${{ inputs.operator-version }}" \
          REVISION="${{ github.sha }}" \
          CREATED="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          TAGS="$TAGS" \
          LABELS="$LABELS"

        # Extract digest for attestation
        DIGEST=$(jq -r '.["containerimage.digest"]' .task/image-metadata.json)
        echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ${{ inputs.registry }}/${{ inputs.image-name }}:v${{ steps.version.outputs.version }}
        format: spdx-json
        output-file: sbom.spdx.json

    - name: Attest SBOM
      uses: actions/attest-sbom@v2
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image-name }}
        subject-digest: ${{ steps.build.outputs.digest }}
        sbom-path: sbom.spdx.json
        push-to-registry: true

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v5
      with:
        name: sbom-operator-v${{ steps.version.outputs.version }}
        path: sbom.spdx.json
        retention-days: 90

    - name: Summary
      shell: bash
      run: |
        echo "### :whale: Operator Image Published" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
