# yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/v1/KeycloakRealm.json
# KeycloakRealm - Identity domain configuration
#
# This file is a REFERENCE EXAMPLE showing all available configuration options.
# For production use, deploy realms using the keycloak-realm Helm chart:
#
#   helm install my-realm oci://ghcr.io/vriesdemichael/charts/keycloak-realm \
#     --namespace my-app --create-namespace \
#     --set realmName=my-app \
#     --set operatorRef.namespace=keycloak-system
#
# The Helm chart automatically creates the required RBAC RoleBinding to grant
# the operator access to your namespace. Using kubectl apply directly will
# result in permission errors unless you manually create the RoleBinding.
#
# Prerequisites:
# - Keycloak instance must be Ready
# - User must have RBAC permission to create KeycloakRealm resources
#
# Operator Compatibility: v1+
# Keycloak Version: 22.0+

apiVersion: vriesdemichael.github.io/v1
kind: KeycloakRealm
metadata:
  name: my-app-realm
  namespace: my-app  # Your application namespace
spec:
  # The actual name of the realm in Keycloak
  realmName: my-app

  # Reference to the Keycloak operator namespace
  operatorRef:
    namespace: keycloak-system

  # Display name shown in Keycloak UI
  displayName: "My Application Realm"

  # Security settings
  security:
    # Allow users to self-register
    registrationAllowed: false

    # Allow password reset via email
    resetPasswordAllowed: true

    # Enable remember me functionality
    rememberMe: true

  # Token and session settings
  tokenSettings:
    # SSO session timeout (30 minutes)
    ssoSessionIdleTimeout: 1800

    # SSO session max lifespan (10 hours)
    ssoSessionMaxLifespan: 36000

  # Optional: SMTP server for email notifications
  # Uncomment and configure for password reset, email verification, etc.
  # smtpServer:
  #   host: smtp.example.com
  #   port: 587
  #   from: noreply@example.com
  #   fromDisplayName: "My App"
  #   replyTo: support@example.com
  #   auth: true
  #   starttls: true
  #   user: smtp-user@example.com
  #   passwordSecret:
  #     name: smtp-password
  #     key: password

  # Optional: Custom themes
  # themes:
  #   loginTheme: my-custom-theme
  #   accountTheme: my-custom-theme
  #   emailTheme: my-custom-theme

  # Optional: Localization
  # localization:
  #   defaultLocale: en
  #   supportedLocales:
  #     - en
  #     - nl
  #     - de
