# KeycloakRealm - Identity domain configuration
#
# This creates a realm (identity domain) in the Keycloak instance.
# A realm contains users, roles, clients, and authentication settings.
#
# Prerequisites:
# - Keycloak instance must be Ready
# - Operator authorization secret must be copied to this namespace

apiVersion: keycloak.mdvr.nl/v1
kind: KeycloakRealm
metadata:
  name: my-app-realm
  namespace: my-app  # Your application namespace
spec:
  # The actual name of the realm in Keycloak
  realmName: my-app

  # Reference to the Keycloak instance
  operatorRef:
    namespace: keycloak-system
    authorizationSecretRef:
      # This secret contains the operator authorization token
      # Copy it from keycloak-system namespace:
      # kubectl get secret keycloak-operator-auth-token -n keycloak-system -o yaml | \
      #   kubectl apply -n my-app -f -
      name: keycloak-operator-auth-token

  # Display name shown in Keycloak UI
  displayName: "My Application Realm"

  # Security settings
  security:
    # Allow users to self-register
    registrationAllowed: false

    # Allow password reset via email
    resetPasswordAllowed: true

    # Enable remember me functionality
    rememberMe: true

  # Session settings
  sessions:
    # SSO session timeout (30 minutes)
    ssoSessionIdleTimeout: 1800

    # SSO session max lifespan (10 hours)
    ssoSessionMaxLifespan: 36000

  # Optional: SMTP server for email notifications
  # Uncomment and configure for password reset, email verification, etc.
  # smtpServer:
  #   host: smtp.example.com
  #   port: 587
  #   from: noreply@example.com
  #   fromDisplayName: "My App"
  #   replyTo: support@example.com
  #   auth: true
  #   starttls: true
  #   user: smtp-user@example.com
  #   passwordSecret:
  #     name: smtp-password
  #     key: password

  # Optional: Custom themes
  # themes:
  #   loginTheme: my-custom-theme
  #   accountTheme: my-custom-theme
  #   emailTheme: my-custom-theme

  # Optional: Localization
  # localization:
  #   defaultLocale: en
  #   supportedLocales:
  #     - en
  #     - nl
  #     - de
