# yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/v1/KeycloakRealm.json
# KeycloakRealm with Custom OIDC Identity Provider
#
# This example shows how to configure a realm with a generic OIDC-compliant
# identity provider. This works with any OpenID Connect provider including
# Okta, Auth0, Keycloak, custom OIDC implementations, etc.
#
# Prerequisites:
# - OIDC Provider configuration (client ID, secret, endpoints)
# - Keycloak instance must be Ready
# - Configure redirect URI in your OIDC provider:
#   https://<keycloak-host>/realms/<realm-name>/broker/custom-oidc/endpoint
#
# Setup Instructions:
# 1. Create OAuth/OIDC application in your identity provider
# 2. Configure redirect URI (see above)
# 3. Obtain client ID, secret, and OIDC discovery endpoints
# 4. Update config section with your provider's endpoints
# 5. Apply this manifest
#
# Operator Compatibility: v1+
# Keycloak Version: 22.0+
---
apiVersion: vriesdemichael.github.io/v1
kind: KeycloakRealm
metadata:
  name: realm-with-custom-oidc-idp
  namespace: my-app
spec:
  realmName: my-realm
  operatorRef:
    namespace: keycloak-operator

  # Generic OIDC Identity Provider (works with any OIDC-compliant provider)
  identityProviders:
    - alias: custom-oidc
      providerId: oidc
      enabled: true
      trustEmail: false
      firstBrokerLoginFlowAlias: first broker login
      config:
        clientId: your-client-id
        clientSecret: your-client-secret
        authorizationUrl: https://idp.example.com/oauth2/authorize
        tokenUrl: https://idp.example.com/oauth2/token
        userInfoUrl: https://idp.example.com/oauth2/userinfo
        jwksUrl: https://idp.example.com/oauth2/keys
        issuer: https://idp.example.com
        defaultScope: "openid profile email"
        syncMode: IMPORT
        validateSignature: "true"
        useJwksUrl: "true"
