# yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/keycloakrealm-vriesdemichael-v1.json
---
apiVersion: vriesdemichael.github.io/v1
kind: KeycloakRealm
metadata:
  name: realm-with-azure-ad-idp
  namespace: my-app
spec:
  realmName: my-realm
  operatorRef:
    namespace: keycloak-operator
    authorizationSecretRef:
      name: my-realm-token

  # Azure AD (Microsoft Entra ID) OIDC Identity Provider
  identityProviders:
    - alias: azure-ad
      providerId: oidc
      enabled: true
      trustEmail: true
      firstBrokerLoginFlowAlias: first broker login
      config:
        clientId: your-azure-app-client-id
        clientSecret: your-azure-app-client-secret
        authorizationUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/authorize
        tokenUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/token
        userInfoUrl: https://graph.microsoft.com/oidc/userinfo
        jwksUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/discovery/v2.0/keys
        issuer: https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0
        defaultScope: "openid profile email"
        syncMode: IMPORT
        validateSignature: "true"
        useJwksUrl: "true"
