# yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/v1/KeycloakRealm.json
# KeycloakRealm with Google Identity Provider
#
# This file is a REFERENCE EXAMPLE. For production use, deploy realms using
# the keycloak-realm Helm chart which handles RBAC automatically.
#
#
# This example shows how to configure a realm with Google OAuth as an identity provider.
# Users will be able to sign in using their Google accounts.
#
# Prerequisites:
# - Google OAuth 2.0 Client ID and Secret (from Google Cloud Console)
# - Keycloak instance must be Ready
# - Kubernetes secret with client secret (see secret example below)
# - Configure authorized redirect URIs in Google:
#   https://<keycloak-host>/realms/<realm-name>/broker/google/endpoint
#
# Setup Instructions:
# 1. Create OAuth 2.0 credentials in Google Cloud Console
# 2. Add authorized redirect URI (see above)
# 3. Create Kubernetes secret with client secret (see example below)
# 4. Apply this manifest
#
# Secret Example:
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: google-idp-secret
#   namespace: my-app
#   labels:
#     vriesdemichael.github.io/keycloak-allow-operator-read: "true"
# type: Opaque
# stringData:
#   clientSecret: your-google-oauth-client-secret
#
# Operator Compatibility: v1+
# Keycloak Version: 22.0+
---
apiVersion: vriesdemichael.github.io/v1
kind: KeycloakRealm
metadata:
  name: realm-with-google-idp
  namespace: my-app
spec:
  realmName: my-realm
  operatorRef:
    namespace: keycloak-operator

  # Google OAuth Identity Provider
  identityProviders:
    - alias: google
      providerId: google
      enabled: true
      trustEmail: true
      firstBrokerLoginFlowAlias: first broker login
      config:
        clientId: your-google-oauth-client-id.apps.googleusercontent.com
        hostedDomain: ""  # Leave empty for all Google accounts, or set to your domain (e.g., "example.com")
        defaultScope: "openid profile email"
        syncMode: IMPORT
      configSecrets:
        clientSecret:
          name: google-idp-secret
          key: clientSecret
