# yaml-language-server: $schema=https://vriesdemichael.github.io/keycloak-operator/schemas/v1/KeycloakRealm.json
# KeycloakRealm with Azure AD (Microsoft Entra ID) Identity Provider
#
# This example shows how to configure a realm with Azure AD / Microsoft Entra ID
# as an OIDC identity provider. Users will be able to sign in using their
# Microsoft work or school accounts.
#
# Prerequisites:
# - Azure AD Application Registration (from Azure Portal)
# - Azure Tenant ID
# - Keycloak instance must be Ready
# - Configure redirect URI in Azure AD:
#   https://<keycloak-host>/realms/<realm-name>/broker/azure-ad/endpoint
#
# Setup Instructions:
# 1. Create App Registration in Azure AD
# 2. Add redirect URI (see above)
# 3. Create client secret in Azure AD
# 4. Replace YOUR_TENANT_ID with your Azure AD tenant ID
# 5. Store client secret in Kubernetes secret (optional, or use plain text)
# 6. Apply this manifest
#
# Operator Compatibility: v1+
# Keycloak Version: 22.0+
---
apiVersion: vriesdemichael.github.io/v1
kind: KeycloakRealm
metadata:
  name: realm-with-azure-ad-idp
  namespace: my-app
spec:
  realmName: my-realm
  operatorRef:
    namespace: keycloak-operator

  # Azure AD (Microsoft Entra ID) OIDC Identity Provider
  identityProviders:
    - alias: azure-ad
      providerId: oidc
      enabled: true
      trustEmail: true
      firstBrokerLoginFlowAlias: first broker login
      config:
        clientId: your-azure-app-client-id
        clientSecret: your-azure-app-client-secret
        authorizationUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/authorize
        tokenUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/oauth2/v2.0/token
        userInfoUrl: https://graph.microsoft.com/oidc/userinfo
        jwksUrl: https://login.microsoftonline.com/YOUR_TENANT_ID/discovery/v2.0/keys
        issuer: https://login.microsoftonline.com/YOUR_TENANT_ID/v2.0
        defaultScope: "openid profile email"
        syncMode: IMPORT
        validateSignature: "true"
        useJwksUrl: "true"
