name: 'Update Operator Chart Version'
description: 'Update the operator chart to use the newly published operator version'

inputs:
  operator-version:
    description: 'Operator version that was just published'
    required: true
  github-token:
    description: 'GitHub PAT token for creating PR (must trigger workflows)'
    required: true
  github-repository:
    description: 'GitHub repository (owner/repo)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-tools

    - name: Update chart values
      shell: bash
      run: |
        task charts:update-version OPERATOR_VERSION="${{ inputs.operator-version }}"
        git diff

    - name: Check for changes
      id: check
      shell: bash
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.check.outputs.changed == 'true'
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github-token }}
        base: main
        commit-message: |
          fix(chart-operator): update for operator v${{ inputs.operator-version }}

          Update operator chart to use operator v${{ inputs.operator-version }}.
          This ensures helm deployments use the latest tested operator image.

          Auto-generated by CI/CD workflow
        branch: chore/update-operator-chart-v${{ inputs.operator-version }}
        delete-branch: true
        title: "fix(chart-operator): update for operator v${{ inputs.operator-version }}"
        body: |
          Updates operator chart to use operator version `v${{ inputs.operator-version }}`.

          **Changes:**
          - Updated `charts/keycloak-operator/values.yaml` image tag
          - Updated `charts/keycloak-operator/Chart.yaml` appVersion

          This fix ensures the chart is compatible with operator v${{ inputs.operator-version }}.

          🤖 Auto-generated by CI/CD workflow
        labels: |
          dependencies
          helm
          automated

    - name: Enable auto-rebase for chart update PR
      if: steps.check.outputs.changed == 'true' && steps.cpr.outputs.pull-request-number
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        PR_NUMBER="${{ steps.cpr.outputs.pull-request-number }}"

        # Enable auto-merge with rebase
        if gh pr merge $PR_NUMBER --auto --rebase --repo ${{ inputs.github-repository }}; then
          echo "### :white_check_mark: Auto-rebase enabled for chart update PR" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "PR #${PR_NUMBER} will merge automatically when checks pass." >> $GITHUB_STEP_SUMMARY
        else
          echo "### :warning: Could not enable auto-rebase" >> $GITHUB_STEP_SUMMARY
        fi
