name: 'Setup Tools'
description: 'Install go-task and yq'

inputs:
  task-version:
    description: 'Task version'
    required: false
    default: 'v3.41.0'
  yq-version:
    description: 'yq version'
    required: false
    default: 'v4.44.3'

runs:
  using: "composite"
  steps:
    - name: Install Task
      shell: bash
      run: |
        if ! command -v task &> /dev/null; then
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin ${{ inputs.task-version }}
        fi

    - name: Install yq
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          wget -q https://github.com/mikefarah/yq/releases/download/${{ inputs.yq-version }}/yq_linux_amd64 -O /tmp/yq
          sudo mv /tmp/yq /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
        fi
