name: 'Setup Tools'
description: 'Install go-task and yq'

inputs:
  task-version:
    description: 'Task version'
    required: false
    default: 'v3.41.0'
  yq-version:
    description: 'yq version'
    required: false
    default: 'v4.44.3'

runs:
  using: "composite"
  steps:
    - name: Install Task
      shell: bash
      run: |
        if ! command -v task &> /dev/null; then
          if ! command -v go &> /dev/null; then
            echo "Go is required to install task but was not found in PATH." >&2
            exit 1
          fi
          GO111MODULE=on GOBIN=/usr/local/bin go install github.com/go-task/task/v3/cmd/task@${{ inputs.task-version }}
        fi

    - name: Install yq
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          set -euo pipefail
          YQ_VERSION="${{ inputs.yq-version }}"
          YQ_BASE_URL="https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}"

          # Download yq binary and its corresponding SHA256 checksum
          wget -q "${YQ_BASE_URL}/yq_linux_amd64" -O /tmp/yq
          wget -q "${YQ_BASE_URL}/yq_linux_amd64.sha256" -O /tmp/yq.sha256

          # Verify checksum before installing
          (cd /tmp && sha256sum -c yq.sha256)

          # Install verified binary
          sudo install -m 0755 /tmp/yq /usr/local/bin/yq
        fi
