name: 'Publish Helm Chart'
description: 'Package and publish a Helm chart to OCI registry with attestation'

inputs:
  chart-name:
    description: 'Name of the chart (keycloak-operator, keycloak-realm, or keycloak-client)'
    required: true
  chart-path:
    description: 'Path to the chart directory'
    required: true
  registry-url:
    description: 'OCI registry URL'
    required: true
  registry-owner:
    description: 'Registry owner/organization'
    required: true
  github-token:
    description: 'GitHub token for registry access'
    required: true
  github-actor:
    description: 'GitHub actor name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Log in to GHCR
      shell: bash
      run: echo "${{ inputs.github-token }}" | helm registry login ${{ inputs.registry-url }} -u ${{ inputs.github-actor }} --password-stdin

    - uses: ./.github/actions/setup-tools

    - name: Package and push chart
      id: push
      shell: bash
      run: |
        task charts:publish \
          CHART_NAME="${{ inputs.chart-name }}" \
          REGISTRY_URL="${{ inputs.registry-url }}" \
          REGISTRY_OWNER="${{ inputs.registry-owner }}"

        # Extract digest for attestation
        DIGEST=$(cat .task/${{ inputs.chart-name }}-digest)
        echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

    - name: Create primary version tag
      if: inputs.chart-name == 'keycloak-operator'
      shell: bash
      run: task charts:tag-primary

    # Docker login is required for attest-build-provenance to push attestations
    # (Helm registry login doesn't share credentials with Docker)
    - name: Log in to GHCR (for attestation)
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Attest chart provenance
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.registry-url }}/${{ inputs.registry-owner }}/charts/${{ inputs.chart-name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
