# Kopf peering resource for leader election
# This resource must exist before the operator starts
apiVersion: kopf.dev/v1
kind: ClusterKopfPeering
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  {{- with include "keycloak-operator.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
