{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  namespace: {{ default (include "keycloak-operator.namespace" .) .Values.monitoring.namespace }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with include "keycloak-operator.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "keycloak-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.interval }}
    scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
    path: /metrics
{{- end }}
