# Example values for keycloak-client chart
# This demonstrates a service account client for machine-to-machine authentication

clientId: myservice
description: "My Service (M2M)"

# Reference to the parent realm
realmRef:
  name: my-realm
  namespace: my-team
  authorizationSecretRef:
    name: my-realm-realm-auth
    key: token

# Client type - confidential client with service account
publicClient: false
bearerOnly: false
protocol: openid-connect

# No redirect URIs needed for service accounts
redirectUris: []
webOrigins: []
postLogoutRedirectUris: []

# Authentication settings
clientAuthenticatorType: client-secret

# Access type - service account only
standardFlowEnabled: false
implicitFlowEnabled: false
directAccessGrantsEnabled: false
serviceAccountsEnabled: true  # Enable service account

# Settings
consentRequired: false
frontchannelLogout: false
authorizationServicesEnabled: false
fullScopeAllowed: false  # Restrict to assigned roles only

settings:
  enabled: true
  accessTokenLifespan: 3600  # 1 hour

# Default scopes for service account
defaultClientScopes:
  - roles

# Service account roles
serviceAccountRoles:
  # Realm-level roles
  realmRoles:
    - view-users
    - query-users

  # Client-level roles
  clientRoles:
    myapp-api:
      - read
      - write

# Protocol mappers
protocolMappers:
  - name: audience-mapper
    protocol: openid-connect
    protocolMapper: oidc-audience-mapper
    config:
      included.client.audience: "myapp-api"
      id.token.claim: "false"
      access.token.claim: "true"

# Secret management
secret:
  generate: true
  secretName: myservice-credentials
  secretKey: client-secret

commonLabels:
  app: myservice
  type: service-account
