apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: namespace
    # Security labels
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted