apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-operator
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: service-account
automountServiceAccountToken: true