name: 'Integration Tests'
description: 'Run integration tests in a Kind cluster with all dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  kind-version:
    description: 'Kind version to use'
    required: false
    default: 'v0.20.0'
  kubectl-version:
    description: 'kubectl version to use'
    required: false
    default: 'v1.30.0'
  node-image:
    description: 'Kind node image'
    required: false
    default: 'kindest/node:v1.30.0'
  cluster-name:
    description: 'Kind cluster name'
    required: true
  kind-config:
    description: 'Path to Kind config file'
    required: false
    default: 'tests/kind/kind-config.yaml'
  registry:
    description: 'Container registry'
    required: true
  image-name:
    description: 'Image name (repository)'
    required: true
  keycloak-version:
    description: 'Keycloak version to use'
    required: true
  github-token:
    description: 'GitHub token for registry access'
    required: true
  codecov-token:
    description: 'Codecov token for uploads'
    required: true
  github-actor:
    description: 'GitHub actor name'
    required: true
  run-id:
    description: 'GitHub run ID for unique naming'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - uses: ./.github/actions/setup-tools

    - name: Download operator image
      uses: actions/download-artifact@v6
      with:
        name: operator-image
        path: /tmp

    - name: Load operator image
      shell: bash
      run: |
        docker load --input /tmp/operator-test.tar
        # Satisfy Taskfile caching
        mkdir -p .task
        touch .task/image_build_operator
        touch .task/image_build_coverage

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Kind
      # We install Kind but don't create the cluster yet - Taskfile handles that
      uses: helm/kind-action@v1.13.0
      with:
        install_only: true
        version: ${{ inputs.kind-version }}
        kubectl_version: ${{ inputs.kubectl-version }}

    - name: Verify Kind installation
      shell: bash
      run: kind version

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Prepare Keycloak optimized image
      shell: bash
      env:
        KEYCLOAK_IMAGE: ${{ inputs.registry }}/${{ inputs.image-name }}/keycloak-optimized:${{ inputs.keycloak-version }}
      run: |
        docker pull "${KEYCLOAK_IMAGE}"
        docker tag "${KEYCLOAK_IMAGE}" keycloak-optimized:${{ inputs.keycloak-version }}
        mkdir -p .task && touch .task/image_build_keycloak

    - name: Prepare Keycloak optimized-tracing image
      shell: bash
      env:
        KEYCLOAK_IMAGE: ${{ inputs.registry }}/${{ inputs.image-name }}/keycloak-optimized-tracing:${{ inputs.keycloak-version }}
      run: |
        docker pull "${KEYCLOAK_IMAGE}"
        docker tag "${KEYCLOAK_IMAGE}" keycloak-optimized-tracing:${{ inputs.keycloak-version }}
        mkdir -p .task && touch .task/image_build_keycloak_tracing

    - name: Load operator image into Kind (Cleanup)
      # Removed: Taskfile handles loading via image:load-operator
      run: echo "Skipped manual load - handled by Taskfile"

    - name: Run integration tests
      shell: bash
      env:
        INTEGRATION_COVERAGE: "true"
        KEYCLOAK_VERSION: ${{ inputs.keycloak-version }}
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        # We let Task create the cluster, so we don't need KIND_RETAIN_CLUSTER here
        # unless we were running in a reused environment.
      run: |
        # Use test:integration-coverage which manages the full lifecycle:
        # 1. Creates cluster (idempotent via kind-setup.sh)
        # 2. Installs infra (CNPG, etc.)
        # 3. Loads images (skips build due to .task/ artifacts)
        # 4. Runs tests
        task test:integration-coverage
        mv coverage.xml coverage-integration.xml

    - name: Upload integration coverage to Codecov
      uses: codecov/codecov-action@v5
      if: always() && inputs.github-actor != 'dependabot[bot]'
      with:
        files: coverage-integration.xml
        flags: integration
        name: integration-tests
        token: ${{ inputs.codecov-token }}
        disable_search: true
        fail_ci_if_error: true

    - name: Upload integration coverage artifact
      uses: actions/upload-artifact@v5
      if: always() && inputs.github-actor != 'dependabot[bot]'
      with:
        name: integration-coverage
        path: |
          coverage-integration.xml
        retention-days: 7

    - name: Collect logs and diagnostics
      if: always()
      shell: bash
      run: task logs:collect

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: test-logs-${{ inputs.run-id }}
        path: test-logs/
        retention-days: 7
