apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakrealms.keycloak.mdvr.nl
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/component: crd
spec:
  group: keycloak.mdvr.nl
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "Keycloak realm configuration for comprehensive identity and access management"
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: "Specification for a Keycloak realm"
            properties:
              # Core realm configuration
              realm_name:
                type: string
                description: "Realm name (must be unique in Keycloak)"
                minLength: 1
                maxLength: 255
              display_name:
                type: string
                description: "Human-readable realm name"
              description:
                type: string
                description: "Realm description"

              # Target configuration
              keycloak_instance_ref:
                type: object
                description: "Reference to the target Keycloak instance"
                properties:
                  name:
                    type: string
                    description: "Name of the Keycloak instance"
                  namespace:
                    type: string
                    description: "Namespace of the Keycloak instance"
                required:
                - name

              # Basic realm settings
              enabled:
                type: boolean
                description: "Whether the realm is enabled"
                default: true

              # Security settings
              security:
                type: object
                description: "Security and authentication settings"
                properties:
                  # Registration and email
                  registration_allowed:
                    type: boolean
                    default: false
                  registration_email_as_username:
                    type: boolean
                    default: false
                  edit_username_allowed:
                    type: boolean
                    default: false
                  reset_password_allowed:
                    type: boolean
                    default: true
                  remember_me:
                    type: boolean
                    default: false
                  verify_email:
                    type: boolean
                    default: false
                  login_with_email_allowed:
                    type: boolean
                    default: true
                  duplicate_emails_allowed:
                    type: boolean
                    default: false
                  # SSL/TLS requirements
                  ssl_required:
                    type: string
                    enum: ["all", "external", "none"]
                    default: "external"
                  # Session and token settings
                  revoke_refresh_token:
                    type: boolean
                    default: false
                  refresh_token_max_reuse:
                    type: integer
                    minimum: 0
                  # Brute force protection
                  brute_force_protected:
                    type: boolean
                    default: false
                  permanent_lockout:
                    type: boolean
                    default: false
                  max_failure_wait:
                    type: integer
                    minimum: 1
                  minimum_quick_login_wait:
                    type: integer
                    minimum: 1
                  wait_increment:
                    type: integer
                    minimum: 1
                  quick_login_check_millis:
                    type: integer
                    minimum: 1
                  max_delta_time:
                    type: integer
                    minimum: 1
                  failure_factor:
                    type: integer
                    minimum: 1

              # Token settings
              tokens:
                type: object
                description: "Token and session configuration"
                properties:
                  access_token_lifespan:
                    type: integer
                    minimum: 1
                    description: "Access token lifespan in seconds"
                  access_token_lifespan_for_implicit_flow:
                    type: integer
                    minimum: 1
                  sso_session_idle_timeout:
                    type: integer
                    minimum: 1
                  sso_session_max_lifespan:
                    type: integer
                    minimum: 1
                  offline_session_idle_timeout:
                    type: integer
                    minimum: 1
                  offline_session_max_lifespan_enabled:
                    type: boolean
                    default: false
                  offline_session_max_lifespan:
                    type: integer
                    minimum: 1
                  client_session_idle_timeout:
                    type: integer
                    minimum: 1
                  client_session_max_lifespan:
                    type: integer
                    minimum: 1
                  client_offline_session_idle_timeout:
                    type: integer
                    minimum: 1
                  client_offline_session_max_lifespan:
                    type: integer
                    minimum: 1

              # Theme configuration
              themes:
                type: object
                description: "Theme configuration"
                properties:
                  login:
                    type: string
                    description: "Login theme"
                  admin:
                    type: string
                    description: "Admin theme"
                  account:
                    type: string
                    description: "Account theme"
                  email:
                    type: string
                    description: "Email theme"

              # Internationalization
              internationalization:
                type: object
                description: "Internationalization settings"
                properties:
                  enabled:
                    type: boolean
                    default: false
                  supported_locales:
                    type: array
                    items:
                      type: string
                  default_locale:
                    type: string

              # Authentication flows
              authentication_flows:
                type: array
                description: "Custom authentication flows"
                items:
                  type: object
                  properties:
                    alias:
                      type: string
                    description:
                      type: string
                    provider_id:
                      type: string
                    top_level:
                      type: boolean
                    built_in:
                      type: boolean
                    execution_config:
                      type: object
                      additionalProperties: true
                  required:
                  - alias

              # Identity providers
              identity_providers:
                type: array
                description: "Identity provider configurations"
                items:
                  type: object
                  properties:
                    alias:
                      type: string
                    provider_id:
                      type: string
                    enabled:
                      type: boolean
                      default: true
                    trust_email:
                      type: boolean
                      default: false
                    store_token:
                      type: boolean
                      default: false
                    add_read_token_role_on_create:
                      type: boolean
                      default: false
                    authenticate_by_default:
                      type: boolean
                      default: false
                    link_only:
                      type: boolean
                      default: false
                    first_broker_login_flow_alias:
                      type: string
                    post_broker_login_flow_alias:
                      type: string
                    config:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                  - alias
                  - provider_id

              # User federation
              user_federation_providers:
                type: array
                description: "User federation provider configurations"
                items:
                  type: object
                  properties:
                    display_name:
                      type: string
                    provider_name:
                      type: string
                    priority:
                      type: integer
                      minimum: 0
                    config:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                  - display_name
                  - provider_name

              # Client scopes
              client_scopes:
                type: array
                description: "Client scope definitions"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    protocol:
                      type: string
                      default: "openid-connect"
                    attributes:
                      type: object
                      additionalProperties:
                        type: string
                    protocol_mappers:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          protocol:
                            type: string
                          protocol_mapper:
                            type: string
                          config:
                            type: object
                            additionalProperties:
                              type: string
                        required:
                        - name
                        - protocol_mapper
                  required:
                  - name

              # Roles
              roles:
                type: object
                description: "Realm and client role definitions"
                properties:
                  realm_roles:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        composite:
                          type: boolean
                          default: false
                        client_role:
                          type: boolean
                          default: false
                        container_id:
                          type: string
                      required:
                      - name

              # Groups
              groups:
                type: array
                description: "Group definitions"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    path:
                      type: string
                    attributes:
                      type: object
                      additionalProperties:
                        type: array
                        items:
                          type: string
                    realm_roles:
                      type: array
                      items:
                        type: string
                    client_roles:
                      type: object
                      additionalProperties:
                        type: array
                        items:
                          type: string
                  required:
                  - name

              # Custom attributes
              attributes:
                type: object
                description: "Additional realm attributes"
                additionalProperties:
                  type: string

              # Events configuration
              events_config:
                type: object
                description: "Event logging configuration"
                properties:
                  events_enabled:
                    type: boolean
                    default: false
                  events_listeners:
                    type: array
                    items:
                      type: string
                  enabled_event_types:
                    type: array
                    items:
                      type: string
                  events_expiration:
                    type: integer
                    minimum: 1
                  admin_events_enabled:
                    type: boolean
                    default: false
                  admin_events_details_enabled:
                    type: boolean
                    default: false

            required:
            - realm_name
            - keycloak_instance_ref

          status:
            type: object
            description: "Current status of the Keycloak realm"
            properties:
              phase:
                type: string
                description: "Current phase"
                enum: ["Pending", "Provisioning", "Ready", "Failed", "Updating"]
              message:
                type: string
              reason:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    last_transition_time:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
              observed_generation:
                type: integer
              # Realm information
              realm_name:
                type: string
              internal_id:
                type: string
              # Connection information
              keycloak_instance:
                type: string
              # Endpoints
              endpoints:
                type: object
                properties:
                  issuer:
                    type: string
                  auth:
                    type: string
                  token:
                    type: string
                  userinfo:
                    type: string
                  jwks:
                    type: string
                  end_session:
                    type: string
                  registration:
                    type: string
              # Feature status
              features:
                type: object
                properties:
                  user_registration:
                    type: boolean
                  password_reset:
                    type: boolean
                  identity_providers:
                    type: integer
                  user_federation_providers:
                    type: integer
                  custom_themes:
                    type: boolean
              # Health monitoring
              last_health_check:
                type: string
                format: date-time
              last_updated:
                type: string
                format: date-time
              # Statistics
              active_users:
                type: integer
                minimum: 0
              total_clients:
                type: integer
                minimum: 0
              realm_roles_count:
                type: integer
                minimum: 0
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Realm
      type: string
      jsonPath: .spec.realm_name
    - name: Keycloak
      type: string
      jsonPath: .status.keycloak_instance
    - name: Users
      type: integer
      jsonPath: .status.active_users
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: keycloakrealms
    singular: keycloakrealm
    kind: KeycloakRealm
    shortNames:
    - kcr